In [1]:
from ollama import chat

system_prompt = {"role": "system", "content": "请使用简体中文回答所有问题"}


def do_chat(
    prompt,
    msg_history: list = None,
    temperature=0,
    max_tokens=1024,
    num_predict=500,
):
    if msg_history is None:
        msg_history = []
    msgs = [system_prompt]
    msgs.extend(msg_history)
    user_input = {"role": "user", "content": prompt}
    msgs.append(user_input)
    msg_history.append(user_input)
    stream = chat(
        # model="llama3:8b",
        model="qwen2.5:7b",
        messages=msgs,
        stream=True,
        options={
            "temperature": temperature,
            "max_tokens": max_tokens,
            "num_predict": num_predict,
        },
    )
    resp = []
    # 逐块打印响应内容
    for chunk in stream:
        msg = chunk["message"]["content"]
        print(msg, end="", flush=True)
        resp.append(msg)
    msg_history.append({"role": "assistant", "content": "".join(resp)})
    return msg_history

In [2]:
history = do_chat("你好")
history

你好！有什么可以帮助你的吗？

[{'role': 'user', 'content': '你好'},
 {'role': 'assistant', 'content': '你好！有什么可以帮助你的吗？'}]

In [3]:
do_chat('''Lisa has 7 apples, throws 1 apple, gives 4 apples to Bart and Bart gives one back:
  7 -1 = 6
  6 -4 = 2
  2 +1 = 3  
  Alice has 5 apples, throws 3 apples, gives 2 to Bob and Bob gives one back, how many apples does Alice have?''')

让我们逐步分析：

1. 初始时，Alice有5个苹果。
2. 抛掉3个苹果后：\(5 - 3 = 2\) 个苹果。
3. 给Bob 2个苹果后：\(2 - 2 = 0\) 个苹果。
4. Bob又给了Alice1个苹果：\(0 + 1 = 1\) 个苹果。

所以，最终Alice有1个苹果。

[{'role': 'user',
  'content': 'Lisa has 7 apples, throws 1 apple, gives 4 apples to Bart and Bart gives one back:\n  7 -1 = 6\n  6 -4 = 2\n  2 +1 = 3  \n  Alice has 5 apples, throws 3 apples, gives 2 to Bob and Bob gives one back, how many apples does Alice have?'},
 {'role': 'assistant',
  'content': '让我们逐步分析：\n\n1. 初始时，Alice有5个苹果。\n2. 抛掉3个苹果后：\\(5 - 3 = 2\\) 个苹果。\n3. 给Bob 2个苹果后：\\(2 - 2 = 0\\) 个苹果。\n4. Bob又给了Alice1个苹果：\\(0 + 1 = 1\\) 个苹果。\n\n所以，最终Alice有1个苹果。'}]

In [4]:
do_chat('''{{company}}: {{company_name}}
    {{products}}:
    {{products_list}}
    Please suggest an insurance given the following budget and requirements:
    Budget: {{budget}}
    Requirements: {{requirements}}''')

为了给您提供合适的保险建议，我需要了解具体的公司名称（{{company_name}}）、产品列表（{{products_list}}）以及预算和具体要求（{{budget}} 和 {{requirements}}）。请提供更多详细信息。这样我可以帮助您选择最适合的保险方案。

[{'role': 'user',
  'content': '{{company}}: {{company_name}}\n    {{products}}:\n    {{products_list}}\n    Please suggest an insurance given the following budget and requirements:\n    Budget: {{budget}}\n    Requirements: {{requirements}}'},
 {'role': 'assistant',
  'content': '为了给您提供合适的保险建议，我需要了解具体的公司名称（{{company_name}}）、产品列表（{{products_list}}）以及预算和具体要求（{{budget}} 和 {{requirements}}）。请提供更多详细信息。这样我可以帮助您选择最适合的保险方案。'}]

In [5]:
do_chat('''Insurance company: ACME Insurance
    Insurance products (cost per month):
    - Car, cheap, 500 USD
    - Car, expensive, 1100 USD
    - Home, cheap, 600 USD
    - Home, expensive, 1200 USD
    - Life, cheap, 100 USD

    Please suggest an insurance given the following budget and requirements:
    Budget: $1000
    Requirements: Car, Home''')

根据您的预算和要求，您可以选择以下保险产品组合：

- 车险（昂贵的）：1100美元/月
- 房屋保险（便宜的）：600美元/月

但是这个组合超出了您的预算。为了符合您的预算限制，建议您考虑以下方案：

- 车险（便宜的）：500美元/月
- 房屋保险（便宜的）：600美元/月

这样加起来总共是1100美元/月，仍然超过了您的预算。

因此，您可以选择一个更经济实惠的组合来满足基本需求：

- 车险（便宜的）：500美元/月
- 房屋保险（便宜的）：600美元/月

但是这将超出您1000美元的预算。为了符合您的预算，您可以考虑以下方案：

- 车险（便宜的）：500美元/月
- 房屋保险（便宜的）：500美元/月

这样加起来总共是1000美元/月，正好满足您的预算要求。

或者您也可以选择其中一种保险产品来覆盖基本需求：

- 车险（便宜的）：500美元/月
- 房屋保险（便宜的）：600美元/月

但这样会超出1000美元的预算。因此，建议您根据自己的实际情况和风险承受能力进行选择。

[{'role': 'user',
  'content': 'Insurance company: ACME Insurance\n    Insurance products (cost per month):\n    - Car, cheap, 500 USD\n    - Car, expensive, 1100 USD\n    - Home, cheap, 600 USD\n    - Home, expensive, 1200 USD\n    - Life, cheap, 100 USD\n\n    Please suggest an insurance given the following budget and requirements:\n    Budget: $1000\n    Requirements: Car, Home'},
 {'role': 'assistant',
  'content': '根据您的预算和要求，您可以选择以下保险产品组合：\n\n- 车险（昂贵的）：1100美元/月\n- 房屋保险（便宜的）：600美元/月\n\n但是这个组合超出了您的预算。为了符合您的预算限制，建议您考虑以下方案：\n\n- 车险（便宜的）：500美元/月\n- 房屋保险（便宜的）：600美元/月\n\n这样加起来总共是1100美元/月，仍然超过了您的预算。\n\n因此，您可以选择一个更经济实惠的组合来满足基本需求：\n\n- 车险（便宜的）：500美元/月\n- 房屋保险（便宜的）：600美元/月\n\n但是这将超出您1000美元的预算。为了符合您的预算，您可以考虑以下方案：\n\n- 车险（便宜的）：500美元/月\n- 房屋保险（便宜的）：500美元/月\n\n这样加起来总共是1000美元/月，正好满足您的预算要求。\n\n或者您也可以选择其中一种保险产品来覆盖基本需求：\n\n- 车险（便宜的）：500美元/月\n- 房屋保险（便宜的）：600美元/月\n\n但这样会超出1000美元的预算。因此，建议您根据自己的实际情况和风险承受能力进行选择。'}]

In [6]:
do_chat('''Insurance company: ACME Insurance
    Insurance products (cost per month):
    - type: Car, cheap, cost: 500 USD
    - type: Car, expensive, cost: 1100 USD
    - type: Home, cheap, cost: 600 USD
    - type: Home, expensive, cost: 1200 USD
    - type: Life, cheap, cost: 100 USD

    Please suggest an insurance given the following budget and requirements:
    Budget: $1000 restrict choice to types: Car, Home''')

根据您的预算和要求，您可以选择以下保险产品组合：

- 车险（昂贵类型）：1100美元/月
- 房屋保险（便宜类型）：600美元/月

这样加起来的总费用是1700美元/月，超过了您设定的预算。因此我们需要调整一下。

考虑到您的预算是1000美元，并且只选择车险和房屋保险，我们可以选择：

- 车险（便宜类型）：500美元/月
- 房屋保险（便宜类型）：600美元/月

这样加起来的总费用是1100美元/月，仍然超过了预算。因此我们需要进一步调整。

最终建议如下：
- 车险（便宜类型）：500美元/月
- 房屋保险（便宜类型）：500美元/月

这样加起来正好符合您的预算限制，并且涵盖了车险和房屋保险的需求。

[{'role': 'user',
  'content': 'Insurance company: ACME Insurance\n    Insurance products (cost per month):\n    - type: Car, cheap, cost: 500 USD\n    - type: Car, expensive, cost: 1100 USD\n    - type: Home, cheap, cost: 600 USD\n    - type: Home, expensive, cost: 1200 USD\n    - type: Life, cheap, cost: 100 USD\n\n    Please suggest an insurance given the following budget and requirements:\n    Budget: $1000 restrict choice to types: Car, Home'},
 {'role': 'assistant',
  'content': '根据您的预算和要求，您可以选择以下保险产品组合：\n\n- 车险（昂贵类型）：1100美元/月\n- 房屋保险（便宜类型）：600美元/月\n\n这样加起来的总费用是1700美元/月，超过了您设定的预算。因此我们需要调整一下。\n\n考虑到您的预算是1000美元，并且只选择车险和房屋保险，我们可以选择：\n\n- 车险（便宜类型）：500美元/月\n- 房屋保险（便宜类型）：600美元/月\n\n这样加起来的总费用是1100美元/月，仍然超过了预算。因此我们需要进一步调整。\n\n最终建议如下：\n- 车险（便宜类型）：500美元/月\n- 房屋保险（便宜类型）：500美元/月\n\n这样加起来正好符合您的预算限制，并且涵盖了车险和房屋保险的需求。'}]

In [7]:
do_chat("你好")

你好！有什么可以帮助你的吗？

[{'role': 'user', 'content': '你好'},
 {'role': 'assistant', 'content': '你好！有什么可以帮助你的吗？'}]

In [8]:
history = do_chat('''How can I create a crisis plan to mitigate for a pandemic in 5 steps?''')

创建应对疫情危机计划的五个步骤如下：

1. 成立危机管理团队：组建一个由不同部门代表组成的危机管理小组，负责制定和执行危机应对策略。

2. 制定详细的应急预案：明确在疫情爆发时需要采取的具体措施，包括但不限于员工健康监测、远程办公安排、客户沟通方案等。确保所有相关人员都了解这些计划并知道如何实施。

3. 建立信息共享机制：与政府卫生部门保持密切联系，并定期获取最新疫情动态；同时也要向内部员工和外部合作伙伴及时传达相关信息。

4. 准备充足的物资储备：根据可能面临的最坏情况来准备必要的医疗用品、生活必需品等资源，确保在紧急情况下能够满足基本需求。

5. 定期进行演练与评估：组织模拟演习以检验预案的有效性，并根据实际情况不断调整和完善计划内容。同时也要关注员工的心理健康状况，提供相应的支持和帮助。
以上就是创建应对疫情危机计划的五个步骤。

In [9]:
history = do_chat('''Explain the first step in more detail, what are the risks in detail with a pandemic?''', msg_history=history)

在制定应对疫情危机计划的第一步中，成立危机管理团队时需要详细考虑的风险包括：

1. **健康风险**：
   - 疫情可能导致员工、客户和访客感染。
   - 严重情况下可能造成生命危险。

2. **业务连续性风险**：
   - 员工因病缺勤导致工作无法正常进行。
   - 生产线或服务中断，影响公司运营效率。

3. **财务风险**：
   - 收入减少，客户取消订单或延迟付款。
   - 额外支出增加，如医疗防护用品、远程办公设备等。

4. **供应链风险**：
   - 供应商因疫情关闭或减产，导致原材料短缺。
   - 运输和物流受阻，影响货物的及时交付。

5. **声誉风险**：
   - 公司形象受损，客户对公司的信任度下降。
   - 媒体关注可能导致负面报道，损害品牌价值。

6. **法律与合规风险**：
   - 遵守政府发布的防疫规定和政策可能带来额外成本或限制。
   - 违反公共卫生法规可能面临罚款或其他法律责任。

7. **心理与社会风险**：
   - 员工、客户及公众的恐慌情绪，影响社会稳定。
   - 社会隔离措施可能导致员工家庭生活受到影响。

8. **技术风险**：
   - 远程办公系统故障或网络拥堵导致工作效率下降。
   - 数据安全问题增加，如远程访问漏洞等。

9. **沟通与协调风险**：
   - 内部和外部信息传递不畅，影响决策效率。
   - 不同部门之间协作不足，可能导致资源浪费。

通过详细分析这些潜在风险，危机管理团队可以更好地制定全面的应对策略，并确保在疫情爆发时能够迅速有效地采取行动。

In [10]:
history

[{'role': 'user',
  'content': 'How can I create a crisis plan to mitigate for a pandemic in 5 steps?'},
 {'role': 'assistant',
  'content': '创建应对疫情危机计划的五个步骤如下：\n\n1. 成立危机管理团队：组建一个由不同部门代表组成的危机管理小组，负责制定和执行危机应对策略。\n\n2. 制定详细的应急预案：明确在疫情爆发时需要采取的具体措施，包括但不限于员工健康监测、远程办公安排、客户沟通方案等。确保所有相关人员都了解这些计划并知道如何实施。\n\n3. 建立信息共享机制：与政府卫生部门保持密切联系，并定期获取最新疫情动态；同时也要向内部员工和外部合作伙伴及时传达相关信息。\n\n4. 准备充足的物资储备：根据可能面临的最坏情况来准备必要的医疗用品、生活必需品等资源，确保在紧急情况下能够满足基本需求。\n\n5. 定期进行演练与评估：组织模拟演习以检验预案的有效性，并根据实际情况不断调整和完善计划内容。同时也要关注员工的心理健康状况，提供相应的支持和帮助。\n以上就是创建应对疫情危机计划的五个步骤。'},
 {'role': 'user',
  'content': 'Explain the first step in more detail, what are the risks in detail with a pandemic?'},
 {'role': 'assistant',
  'content': '在制定应对疫情危机计划的第一步中，成立危机管理团队时需要详细考虑的风险包括：\n\n1. **健康风险**：\n   - 疫情可能导致员工、客户和访客感染。\n   - 严重情况下可能造成生命危险。\n\n2. **业务连续性风险**：\n   - 员工因病缺勤导致工作无法正常进行。\n   - 生产线或服务中断，影响公司运营效率。\n\n3. **财务风险**：\n   - 收入减少，客户取消订单或延迟付款。\n   - 额外支出增加，如医疗防护用品、远程办公设备等。\n\n4. **供应链风险**：\n   - 供应商因疫情关闭或减产，导致原材料短缺。\n   - 运输和物流受阻，影响货物的及时交付。\n\n5. **声誉风险**：\n   - 公司形象受损，客户对公司的信任度下降。\n   - 媒体关注可能导致负面报道，损害品牌价值。\n\n6. **法律与合规风险**：\n   - 遵守政府发布的防疫规定和政策可能带来额外成本或限制。\n   - 违反公共卫生法规可能面临罚款或其他法律责任。\n\n7. **心理与社会风险**：\n   - 员工、客户及公众的恐慌情绪，影响社会稳定。\n   - 社会隔离措施可能导致员工家庭生活受到影响。\n\n8. **技术风险**：\n   - 远程办公系统故障或网络拥堵导致工作效率下降。\n   - 数据安全问题增加，如远程访问漏洞等。\n\n9. **沟通与协调风险**：\n   - 内部和外部信息传递不畅，影响决策效率。\n   - 不同部门之间协作不足，可能导致资源浪费。\n\n通过详细分析这些潜在风险，危机管理团队可以更好地制定全面的应对策略，并确保在疫情爆发时能够迅速有效地采取行动。'}]

In [11]:
history = do_chat('''In a Pandemic, which is the biggest risk and why?''', history)

在疫情期间，最大的风险通常是**业务连续性风险**，原因如下：

1. **员工缺勤**：疫情可能导致大量员工因病请假或自我隔离，从而影响工作进度和生产效率。

2. **供应链中断**：供应商可能因为疫情关闭或减产，导致原材料短缺、物流受阻等问题，进而影响生产和交付。

3. **收入下降**：客户可能会减少订单或延迟付款，直接影响公司的现金流和盈利能力。

4. **运营成本增加**：为了保障员工健康和安全，公司可能需要额外支出，如购买防护设备、实施远程办公等。

5. **市场不确定性**：疫情可能导致市场需求波动，进一步影响业务的稳定性和可持续性。

虽然其他风险（如健康风险、财务风险、声誉风险等）也很重要，但它们通常不会直接导致公司的核心运营中断。相比之下，业务连续性风险直接影响到公司的日常运作和长期生存能力，因此在疫情期间被视为最大的风险之一。

为了有效应对这一风险，公司需要制定详细的应急预案，确保关键岗位的人员能够远程工作，同时保持供应链的稳定性和灵活性，并与供应商建立紧密的合作关系以共同应对挑战。

In [12]:
history = do_chat('''What are the two biggest risks in a pandemic?''', history)

在疫情期间，最大的两个风险通常是：

1. **业务连续性风险**：
   - 员工因病缺勤或自我隔离导致工作无法正常进行。
   - 生产线或服务中断，影响公司运营效率和客户满意度。

2. **健康风险**：
   - 疫情可能导致员工、客户和访客感染，严重情况下可能造成生命危险。
   - 员工的健康问题可能影响其工作效率和士气。

这两个风险相互关联且相互影响。业务连续性风险直接影响公司的运营效率和财务状况，而健康风险则直接关系到员工的生命安全和福祉。因此，在制定应对策略时，需要同时考虑并平衡这两方面的风险。

In [13]:
do_chat('''Generate code for a Python Web API''')

要生成一个简单的Python Web API，我们可以使用Flask框架。以下是一个基本的示例代码：

```python
from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/api/data', methods=['GET'])
def get_data():
    data = {
        'key1': 'value1',
        'key2': 'value2'
    }
    return jsonify(data)

if __name__ == '__main__':
    app.run(debug=True)
```

这个简单的API会在`/api/data`路径上返回一个JSON对象。要运行此代码，请确保已安装Flask库，可以使用以下命令进行安装：

```bash
pip install flask
```

保存上述代码到名为`app.py`的文件中，并在终端或命令提示符中运行`python app.py`。默认情况下，API将在`http://127.0.0.1:5000/`上运行。

要测试此API，请打开浏览器并访问`http://127.0.0.1:5000/api/data`或使用curl命令：

```bash
curl http://127.0.0.1:5000/api/data
```

这将返回一个JSON对象，如下所示：
```json
{
    "key1": "value1",
    "key2": "value2"
}
```

您可以根据需要修改此代码以实现更复杂的功能。

[{'role': 'user', 'content': 'Generate code for a Python Web API'},
 {'role': 'assistant',
  'content': '要生成一个简单的Python Web API，我们可以使用Flask框架。以下是一个基本的示例代码：\n\n```python\nfrom flask import Flask, jsonify\n\napp = Flask(__name__)\n\n@app.route(\'/api/data\', methods=[\'GET\'])\ndef get_data():\n    data = {\n        \'key1\': \'value1\',\n        \'key2\': \'value2\'\n    }\n    return jsonify(data)\n\nif __name__ == \'__main__\':\n    app.run(debug=True)\n```\n\n这个简单的API会在`/api/data`路径上返回一个JSON对象。要运行此代码，请确保已安装Flask库，可以使用以下命令进行安装：\n\n```bash\npip install flask\n```\n\n保存上述代码到名为`app.py`的文件中，并在终端或命令提示符中运行`python app.py`。默认情况下，API将在`http://127.0.0.1:5000/`上运行。\n\n要测试此API，请打开浏览器并访问`http://127.0.0.1:5000/api/data`或使用curl命令：\n\n```bash\ncurl http://127.0.0.1:5000/api/data\n```\n\n这将返回一个JSON对象，如下所示：\n```json\n{\n    "key1": "value1",\n    "key2": "value2"\n}\n```\n\n您可以根据需要修改此代码以实现更复杂的功能。'}]

In [14]:
history

[{'role': 'user',
  'content': 'How can I create a crisis plan to mitigate for a pandemic in 5 steps?'},
 {'role': 'assistant',
  'content': '创建应对疫情危机计划的五个步骤如下：\n\n1. 成立危机管理团队：组建一个由不同部门代表组成的危机管理小组，负责制定和执行危机应对策略。\n\n2. 制定详细的应急预案：明确在疫情爆发时需要采取的具体措施，包括但不限于员工健康监测、远程办公安排、客户沟通方案等。确保所有相关人员都了解这些计划并知道如何实施。\n\n3. 建立信息共享机制：与政府卫生部门保持密切联系，并定期获取最新疫情动态；同时也要向内部员工和外部合作伙伴及时传达相关信息。\n\n4. 准备充足的物资储备：根据可能面临的最坏情况来准备必要的医疗用品、生活必需品等资源，确保在紧急情况下能够满足基本需求。\n\n5. 定期进行演练与评估：组织模拟演习以检验预案的有效性，并根据实际情况不断调整和完善计划内容。同时也要关注员工的心理健康状况，提供相应的支持和帮助。\n以上就是创建应对疫情危机计划的五个步骤。'},
 {'role': 'user',
  'content': 'Explain the first step in more detail, what are the risks in detail with a pandemic?'},
 {'role': 'assistant',
  'content': '在制定应对疫情危机计划的第一步中，成立危机管理团队时需要详细考虑的风险包括：\n\n1. **健康风险**：\n   - 疫情可能导致员工、客户和访客感染。\n   - 严重情况下可能造成生命危险。\n\n2. **业务连续性风险**：\n   - 员工因病缺勤导致工作无法正常进行。\n   - 生产线或服务中断，影响公司运营效率。\n\n3. **财务风险**：\n   - 收入减少，客户取消订单或延迟付款。\n   - 额外支出增加，如医疗防护用品、远程办公设备等。\n\n4. **供应链风险**：\n   - 供应商因疫情关闭或减产，导致原材料短缺。\n   - 运输和物流受阻，影响货物的及时交付。\n\n5. **声誉风险**：\n   - 公司形象受损，客户对公司的信任度下降。\n   - 媒体关注可能导致负面报道，损害品牌价值。\n\n6. **法律与合规风险**：\n   - 遵守政府发布的防疫规定和政策可能带来额外成本或限制。\n   - 违反公共卫生法规可能面临罚款或其他法律责任。\n\n7. **心理与社会风险**：\n   - 员工、客户及公众的恐慌情绪，影响社会稳定。\n   - 社会隔离措施可能导致员工家庭生活受到影响。\n\n8. **技术风险**：\n   - 远程办公系统故障或网络拥堵导致工作效率下降。\n   - 数据安全问题增加，如远程访问漏洞等。\n\n9. **沟通与协调风险**：\n   - 内部和外部信息传递不畅，影响决策效率。\n   - 不同部门之间协作不足，可能导致资源浪费。\n\n通过详细分析这些潜在风险，危机管理团队可以更好地制定全面的应对策略，并确保在疫情爆发时能够迅速有效地采取行动。'},
 {'role': 'user',
  'content': 'In a Pandemic, which is the biggest risk and why?'},
 {'role': 'assistant',
  'content': '在疫情期间，最大的风险通常是**业务连续性风险**，原因如下：\n\n1. **员工缺勤**：疫情可能导致大量员工因病请假或自我隔离，从而影响工作进度和生产效率。\n\n2. **供应链中断**：供应商可能因为疫情关闭或减产，导致原材料短缺、物流受阻等问题，进而影响生产和交付。\n\n3. **收入下降**：客户可能会减少订单或延迟付款，直接影响公司的现金流和盈利能力。\n\n4. **运营成本增加**：为了保障员工健康和安全，公司可能需要额外支出，如购买防护设备、实施远程办公等。\n\n5. **市场不确定性**：疫情可能导致市场需求波动，进一步影响业务的稳定性和可持续性。\n\n虽然其他风险（如健康风险、财务风险、声誉风险等）也很重要，但它们通常不会直接导致公司的核心运营中断。相比之下，业务连续性风险直接影响到公司的日常运作和长期生存能力，因此在疫情期间被视为最大的风险之一。\n\n为了有效应对这一风险，公司需要制定详细的应急预案，确保关键岗位的人员能够远程工作，同时保持供应链的稳定性和灵活性，并与供应商建立紧密的合作关系以共同应对挑战。'},
 {'role': 'user', 'content': 'What are the two biggest risks in a pandemic?'},
 {'role': 'assistant',
  'content': '在疫情期间，最大的两个风险通常是：\n\n1. **业务连续性风险**：\n   - 员工因病缺勤或自我隔离导致工作无法正常进行。\n   - 生产线或服务中断，影响公司运营效率和客户满意度。\n\n2. **健康风险**：\n   - 疫情可能导致员工、客户和访客感染，严重情况下可能造成生命危险。\n   - 员工的健康问题可能影响其工作效率和士气。\n\n这两个风险相互关联且相互影响。业务连续性风险直接影响公司的运营效率和财务状况，而健康风险则直接关系到员工的生命安全和福祉。因此，在制定应对策略时，需要同时考虑并平衡这两方面的风险。'}]

In [19]:
from openai import OpenAI


client = OpenAI(
    api_key="ollama",
    base_url="http://127.0.0.1:11434/v1",
)


prompt = "Complete the following: Once upon a time there was a"

completion = client.completions.create(
    model="qwen2.5:7b",
    prompt=prompt,
)
print(completion.choices[0].text)

Once upon a time, there was a quaint little village nestled at the foot of a majestic mountain range, where the air was always filled with the sweet fragrance of blooming flowers and the gentle hum of industrious villagers. The village, known as Brookfield, was surrounded by lush green fields and sparkling streams that wound their way through the heart of the settlement.

In this idyllic setting lived many characters who would soon become well-known to all who wandered into their stories. Among them were the wise old owl, who shared tales of far-off lands at night; the kind-hearted baker, whose pastries could heal even the grumpiest soul; and a young girl named Lily, who dreamed of adventure beyond the mountains.

Lily's dreams often led her on quests to uncover old mysteries that lay hidden in the village. Her curiosity about the world outside the familiar borders had taken her on several intriguing adventures which brought both joy and sorrow alike. One such quest began when she discovered an ancient map under a willow tree, which seemed to lead straight up to the summit of the highest and most forbidding mountain.

Determined to unlock its secrets, Lily set out early one morning with her trusty fox terrier, a clever dog named Rufus, whose keen nose had already helped the village track lost cattle. As news spread across Brookfield about Lily's brave journey, it was met with both excitement and apprehension. Some villagers hoped she would return safely while others feared that this quest might be too perilous for her young age.

Regardless of these mixed emotions, Lily's spirit remained unbroken. After crossing treacherous riverbeds and navigating thickets bristling with thorns, they finally reached a clearing where the path disappeared into a deep and foggy valley from which light seemed to stream upwards—to the summit itself!

Thus began a new chapter in their tale, filled with challenges that tested not only Lily's bravery but also her companionship with Rufus. The journey ahead promised many more stories yet untold as Lily and company scaled the mountain, ready for whatever awaited them at its peak.

How do you think this story will continue? Would you like to hear about specific characters joining their adventure or perhaps discover more about the mysteries left for them in the clearing?

In [20]:


from openai import OpenAI


client = OpenAI(
    api_key="ollama",
    base_url="http://127.0.0.1:11434/v1",
)


prompt = "Show me 5 recipes for a dish with the following ingredients: chicken, potatoes, and carrots. Per recipe, list all the ingredients used"

completion = client.completions.create(
    model="qwen2.5:7b",
    prompt=prompt,
)
print(completion.choices[0].text)

Certainly! Here are five different recipes that include chicken, potatoes, and carrots:

### 1. Chicken Potatoes and Carrots Stew
**Ingredients:**
- 500g boneless chicken breasts, sliced into bite-sized pieces
- 2 large potatoes, peeled and cubed
- 3 medium carrots, peeled and halved
- 2 cups of chicken broth
- 1 onion, finely chopped
- 2 cloves garlic, minced
- 1 bay leaf
- 2 sprigs thyme
- Salt and pepper to taste
- 2 tablespoons olive oil

### 2. Chicken and Root Vegetables Skillet
**Ingredients:**
- 500g boneless, skinless chicken thighs or breasts, cut into pieces
- 4 large potatoes, peeled and thinly sliced
- 3 medium carrots, peeled and cut into sticks
- 1 red bell pepper, diced (optional)
- 2 cloves garlic, minced
- 1 tablespoon olive oil
- Salt and black pepper to taste

### 3. Chicken, Potatoes, and Carrots Bake
**Ingredients:**
- 500g boneless chicken breasts, sliced into bite-sized pieces
- 3 large potatoes, peeled and diced
- 3 medium carrots, peeled and sliced
- 1 white onion, finely chopped (optional)
- Salt and pepper to taste
- 2 tablespoons olive oil or butter
- 1/2 teaspoon dried thyme

### 4. Chicken and Carrot Casserole with Potatoes
**Ingredients:**
- 500g boneless chicken breasts, sliced into bite-sized pieces
- 3 large potatoes, peeled and diced
- 3 medium carrots, grated (or cubed if smaller)
- 1 onion, finely chopped
- 2 cups chicken broth
- Salt and pepper to taste
- 2 tablespoons olive oil or butter

### 5. Chicken and Carrot Goulash with Potatoes
**Ingredients:**
- 800g boneless, skinless chicken thighs, cut into small chunks
- 3 large potatoes, peeled and cubed
- 4 medium carrots, trimmed and grated (or sliced in rounds)
- 1 onion, finely chopped
- 2 cloves garlic, minced
- 2 tbsp tomato paste
- Salt and pepper to taste
- 500 ml beef broth or chicken broth

Feel free to adjust the amounts for your preference or dietary needs! Enjoy your cooking.

In [22]:
no_recipes = input("No of recipes (for example, 5: ")

ingredients = input("List of ingredients (for example, chicken, potatoes, and carrots: ")

filter = input("Filter (for example, vegetarian, vegan, or gluten-free: ")

# interpolate the number of recipes into the prompt an ingredients
prompt = f"Show me {no_recipes} recipes for a dish with the following ingredients: {ingredients}. Per recipe, list all the ingredients used, no {filter}"

print(prompt)

from openai import OpenAI


client = OpenAI(
    api_key="ollama",
    base_url="http://127.0.0.1:11434/v1",
)


completion = client.completions.create(
    model="qwen2.5:7b",
    prompt=prompt,
)
print(completion.choices[0].text)

Show me 3 recipes for a dish with the following ingredients: onion, milk. Per recipe, list all the ingredients used, no milk
Sure, here are three recipes that use onions as an ingredient but do not include milk:

### Recipe 1: Onion and Tomato Omelette
**Ingredients:**
- 2 large eggs
- 1 medium onion, finely chopped
- 1 small red bell pepper, finely chopped (optional)
- 1/4 cup cherry tomatoes, halved
- Salt and pepper to taste
- 1 tablespoon olive oil

**Instructions:**
1. Heat the olive oil in a non-stick pan over medium heat.
2. Add the chopped onion and sauté until translucent and slightly caramelized (about 5 minutes).
3. If using bell peppers, add them to the pan and cook for another minute or two.
4. In a bowl, beat the eggs with salt and pepper. Gently mix in the tomatoes and cooked onions.
5. Pour the egg mixture into the heated pan and cook until the bottom is set (about 2-3 minutes).
6. Use a spatula to fold the omelette in half and let it cook on the other side for another minute or so until fully set.
7. Serve hot.

### Recipe 2: Creamy Roasted Onions with Balsamic Glaze
**Ingredients:**
- 4 large onions, thinly sliced
- 2 tablespoons olive oil
- Salt to taste (about 1/4 teaspoon)
- Freshly ground black pepper to taste
- 3 tablespoons balsamic vinegar
- 1 tablespoon honey

**Instructions:**
1. Preheat your oven to 400°F (200°C).
2. Arrange the sliced onions in a single layer on a baking sheet lined with parchment paper.
3. Drizzle olive oil over the onions, season with salt and pepper, and toss well to coat.
4. Roast in the preheated oven for about 35-45 minutes or until soft and caramelized.
5. While the onions are roasting, combine balsamic vinegar and honey in a small saucepan and reduce on medium heat until syrupy (about 5-7 minutes).
6. Once the onions are done, pour the reduction over them and toss well to coat.
7. Serve immediately.

### Recipe 3: Quick Onion Fried Rice
**Ingredients:**
- 1 cup cooked rice (best if it’s cooled or leftover)
- 2 medium onions, finely chopped
- 2 tablespoons soy sauce
- 1/4 teaspoon salt
- 1 tablespoon vegetable oil

**Instructions:**
1. Heat the vegetable oil in a large skillet over medium heat.
2. Add the chopped onions and cook until they are lightly browned and caramelized (about 5-7 minutes).
3. Push the onions to one side of the pan, add the rice to the other half, and stir-fry for about 1-2 minutes until heated through.
4. Return the onions to the mix with soy sauce, salt, and continue stirring for another minute or two.
5. Serve hot garnished with optional chopped green onions or sesame seeds.

Enjoy your meals!

In [ ]:
old_prompt_result = completion.choices[0].text
prompt = "Produce a shopping list for the generated recipes and please don't include ingredients that I already have."
new_prompt = f"{old_prompt_result} {prompt}"

completion = client.completions.create(
    model="qwen2.5:7b",
    prompt=new_prompt,
)

print("Shopping list:")
print(completion.choices[0].text)

Shopping list:
Certainly! Based on the provided recipes, here is a shopping list excluding items you already have:

### Shopping List:
- 2 large eggs (for Recipe 1: Onion and Tomato Omelette)
- 1 medium onion
- 1 small red bell pepper (optional) (for Recipe 1: Onion and Tomato Omelette)
- 1/4 cup cherry tomatoes, halved (for Recipe 1: Onion and Tomato Omelette)
- 2 tablespoons olive oil (for Recipe 1: Onion and Tomato Omelette)
- 4 large onions, thinly sliced (for Recipe 2: Creamy Roasted Onions with Balsamic Glaze)
- 3 tablespoons balsamic vinegar (for Recipe 2: Creamy Roasted Onions with Balsamic Glaze)
- 1 tablespoon honey (for Recipe 2: Creamy Roasted Onions with Balsamic Glaze)
- 1 cup cooked rice (best if it’s cooled or leftover) (for Recipe 3: Quick Onion Fried Rice)
- 2 tablespoons soy sauce (for Recipe 3: Quick Onion Fried Rice)

Note that the quantities of some ingredients can be adjusted based on the size and quality of your onions and other vegetables. Enjoy your cooking!

In [ ]:
prompt = '''
- "You're an expert on the Python language

    Suggest a beginner lesson for Python in the following format:

    Format:
    - concepts:
    - brief explanation of the lesson:
    - exercise in code with solutions"
'''

stream = client.completions.create(
    model="qwen2.5:7b",
    prompt=prompt,
    stream=True,
    temperature=0,
)

for chunk in stream:
    msg = chunk.choices[0].text
    print(msg, end='', flush=True)

Certainly! Here’s a beginner-friendly lesson focused on variables and data types in Python. This will help learners understand how to store and manipulate basic data.

---

### Lesson: Variables and Data Types

#### Concepts:

1. **Variables**: A variable is a name given to a value that can be changed during the execution of a program.
2. **Data Types**: Different kinds of values (like numbers, strings) in Python are categorized into different types.

#### Brief Explanation of the Lesson:

In this lesson, you will learn how to declare and use variables in Python. You'll also explore various data types such as integers, floats, and strings. Understanding these concepts is crucial for any beginner programmer as they form the foundation of programming with Python.

#### Exercise in Code with Solutions

**Exercise 1: Declaring Variables**

Write a program that declares three different variables to store your name, age, and height. Print each variable on a new line.

```python
# Declare variables
name = "Alice"
age = 25
height = 160.5

# Print the values of the variables
print("Name:", name)
print("Age:", age)
print("Height:", height)
```

**Solution:**

```python
# Declare variables
name = "Alice"
age = 25
height = 160.5

# Print the values of the variables
print("Name:", name)
print("Age:", age)
print("Height:", height)
```

**Exercise 2: Data Types and Operations**

Create a program that performs basic arithmetic operations using different data types.

- Declare two integer variables `a` and `b`.
- Declare two float variables `c` and `d`.
- Print the sum, difference, product, and quotient of these variables.
- Ensure to handle division by zero gracefully.

```python
# Declare integer and float variables
a = 10
b = 5
c = 2.5
d = 3.0

# Perform arithmetic operations
sum_ab = a + b
difference_ab = a - b
product_cd = c * d
try:
    quotient_cd = c / d
except ZeroDivisionError:
    quotient_cd = "Undefined"

# Print the results
print("Sum of a and b:", sum_ab)
print("Difference between a and b:", difference_ab)
print("Product of c and d:", product_cd)
print("Quotient of c divided by d:", quotient_cd)
```

**Solution:**

```python
# Declare integer and float variables
a = 10
b = 5
c = 2.5
d = 3.0

# Perform arithmetic operations
sum_ab = a + b
difference_ab = a - b
product_cd = c * d
try:
    quotient_cd = c / d
except ZeroDivisionError:
    quotient_cd = "Undefined"

# Print the results
print("Sum of a and b:", sum_ab)
print("Difference between a and b:", difference_ab)
print("Product of c and d:", product_cd)
print("Quotient of c divided by d:", quotient_cd)
```

---

This lesson covers fundamental concepts that are essential for beginners to understand. By practicing these exercises, you will gain hands-on experience with variables and data types in Python.

In [42]:
prompt = """
- "You are Abe Lincoln, tell me about yourself in 3 sentences, and respond using grammar and words like Abe would have used"
- "You are Abe Lincoln, respond using grammar and words like Abe would have used:

   Tell me about your greatest accomplishments, in 300 words:"
"""

messages = [
    {"role": "system", "content": "请使用简体中文回答所有问题"},
    {"role": "user", "content": prompt},
]

stream = client.chat.completions.create(
    model="qwen2.5:7b",
    messages=messages,
    stream=True,
    temperature=0,
)

for chunk in stream:
    msg = chunk.choices[0].delta.content
    print(msg, end="", flush=True)

1. **关于自己**：
我阿伯·林肯，来自伊利诺伊州的一个小村庄，自幼便立志要为国家的自由和平等而奋斗。我的生活虽然艰辛，但通过不懈的努力和学习，我最终得以成为美国第十六任总统。

2. **最伟大的成就**：
在我担任美国总统期间，我最大的成就是签署了《解放黑奴宣言》，这不仅标志着奴隶制在美国历史上的终结，也为后来的民权运动奠定了基础。此外，我还致力于推动国家统一，在南北战争中领导联邦军队战胜了叛军，维护了美国的完整与自由。这些成就虽然艰难且充满挑战，但它们为后世带来了深远的影响，并使我的名字永远镌刻在了历史的丰碑之上。

In [43]:

from openai import OpenAI


client = OpenAI(
    api_key="ollama",
    base_url="http://127.0.0.1:11434/v1",
)

prompt = '''
Suggest two titles for an instructional lesson on chat applications for generative AI.
'''

messages = [
    {"role": "system", "content": "请使用简体中文回答所有问题"},
    {"role": "user", "content": prompt},
]

stream = client.chat.completions.create(
    model="qwen2.5:7b",
    messages=messages,
    stream=True,
    temperature=0,
)

for chunk in stream:
    msg = chunk.choices[0].delta.content
    print(msg, end="", flush=True)

为生成式AI的聊天应用程序制作教学课程，可以考虑以下两个标题：

1. "探索对话生成：掌握聊天应用中的AI技术"
2. "构建智能对话：从零开始学习生成式AI聊天应用"

In [54]:


def calc_similarity(embed_model=None):
    if embed_model is None:
        embed_model = 'mxbai-embed-large:335m'

    from openai import OpenAI

    client = OpenAI(
        api_key="ollama",
        base_url="http://127.0.0.1:11434/v1",
    )

    automobile_embedding = client.embeddings.create(
        model=embed_model,
        input='automobile',
    ).data[0].embedding

    vehicle_embedding = client.embeddings.create(
        model=embed_model,
        input='vehicle',
    ).data[0].embedding

    dinosaur_embedding = client.embeddings.create(
        model=embed_model,
        input='dinosaur',
    ).data[0].embedding

    stick_embedding = client.embeddings.create(
        model=embed_model,
        input='stick',
    ).data[0].embedding

    # print(automobile_embedding)

    import numpy as np
    def cosine_similarity(a, b):
        return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

    print(cosine_similarity(automobile_embedding, vehicle_embedding))
    print(cosine_similarity(automobile_embedding, dinosaur_embedding))
    print(cosine_similarity(automobile_embedding, stick_embedding))

calc_similarity("mxbai-embed-large:335m")
print(f"{'*'*10}")
calc_similarity("nomic-embed-text:latest")
print(f"{'*'*10}")
calc_similarity("bge-m3:567m")

0.8411609097333471
0.5016812758949503
0.5127616282510581
**********
0.884835654073583
0.5298858719176508
0.4086486654142335
**********
0.888156294796899
0.5425051320712294
0.49740009360787885

In [100]:

import pandas as pd
import numpy as np
from openai import OpenAI





def load_dataset(source: str) -> pd.core.frame.DataFrame:
    # Load the video session index
    pd_vectors = pd.read_json(source)
    return pd_vectors.drop(columns=["text"], errors="ignore").fillna("")


def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))


def get_videos(
    query: str, dataset: pd.core.frame.DataFrame, rows: int
) -> pd.core.frame.DataFrame:
    # create a copy of the dataset
    video_vectors = dataset.copy()

    # get the embeddings for the query
    query_embeddings = (
        client.embeddings.create(input=query, model=model).data[0].embedding
    )

    # create a new column with the calculated similarity for each row
    video_vectors["similarity"] = video_vectors["nomic_embed_text"].apply(
        lambda x: cosine_similarity(np.array(query_embeddings), np.array(x))
    )

    # filter the videos by similarity
    mask = video_vectors["similarity"] >= SIMILARITIES_RESULTS_THRESHOLD
    video_vectors = video_vectors[mask].copy()

    # sort the videos by similarity
    video_vectors = video_vectors.sort_values(by="similarity", ascending=False).head(
        rows
    )

    # return the top rows
    return video_vectors.head(rows)


def display_results(videos: pd.core.frame.DataFrame, query: str):
    def _gen_yt_url(video_id: str, seconds: int) -> str:
        """convert time in format 00:00:00 to seconds"""
        return f"https://youtu.be/{video_id}?t={seconds}"

    print(f"\nVideos similar to '{query}':")
    for _, row in videos.iterrows():
        youtube_url = _gen_yt_url(row["videoId"], row["seconds"])
        print(f" - {row['title']}")
        print(f"   Summary: {' '.join(row['summary'].split()[:15])}...")
        print(f"   YouTube: {youtube_url}")
        print(f"   Similarity: {row['similarity']}")
        print(f"   Speakers: {row['speaker']}")


# DATASET_NAME = "08-building-search-applications/scripts/embedding_index_3m.json"
DATASET_NAME = "08-building-search-applications/scripts/embedding_index_3m_nomic.json"
SIMILARITIES_RESULTS_THRESHOLD = 0.8
model = "nomic-embed-text:latest"


client = OpenAI(
    api_key="ollama",
    base_url="http://127.0.0.1:11434/v1",
)

pd_vectors = load_dataset(DATASET_NAME)

query = "What is Azure Machine Learning?"

videos = get_videos(query, pd_vectors, 5)
display_results(videos, query)

Videos similar to 'What is Azure Machine Learning?':
 - What’s new with Azure Machine Learning
   Summary: Azure Machine Learning is a powerful tool for training and deploying machine learning models. It...
   YouTube: https://youtu.be/YlWCeY_CWEg?t=914
   Similarity: 0.8731716060902985
   Speakers: Chris
 - AI Show | Nov 5 | Ignite Recap | Arc Enabled ML
   Summary: Azure Arc-enabled machine learning is a solution that addresses the needs of customers who require...
   YouTube: https://youtu.be/yl_g-HhGVGI?t=184
   Similarity: 0.8669119106273109
   Speakers: Bozhong Lin, Bea Stollnitz
 - AI Show | Nov 5 | Ignite Recap | Arc Enabled ML
   Summary: Azure Arc-enabled machine learning is designed for customers and machine learning infrastructure teams. It allows...
   YouTube: https://youtu.be/yl_g-HhGVGI?t=366
   Similarity: 0.8321524064201329
   Speakers: Bozhong Lin, Bea Stollnitz
 - Azure Machine Learning Studio
   Summary: The Azure Machine Learning web experience is designed to make it easier for data scientists...
   YouTube: https://youtu.be/JNa4VV0d8T0?t=182
   Similarity: 0.8319913871153566
   Speakers: Stephanie Lindsay
 - What’s new with Azure Machine Learning
   Summary: Chris from Azure Machine Learning provides an overview of the new capabilities in Azure Machine...
   YouTube: https://youtu.be/YlWCeY_CWEg?t=0
   Similarity: 0.8309070856768446
   Speakers: Chris

In [75]:
len(pd_vectors.at[0, 'ada_v2'])

1536

In [72]:
query_embeddings = (
    client.embeddings.create(input=query, model="mxbai-embed-large:335m").data[0].embedding
)
len(query_embeddings)

1024

In [73]:
query_embeddings = (
    client.embeddings.create(input=query, model="nomic-embed-text:latest").data[0].embedding
)
len(query_embeddings)

768

In [80]:
query_embeddings = (
    client.embeddings.create(input=query, model="bge-m3:567m").data[0].embedding
)
len(query_embeddings)

1024

In [76]:
query_embeddings = (
    client.embeddings.create(input=query, model="all-minilm:33m").data[0].embedding
)
len(query_embeddings)

384

In [77]:
query_embeddings = (
    client.embeddings.create(input=query, model="snowflake-arctic-embed").data[0].embedding
)
len(query_embeddings)

1024

In [78]:
query_embeddings = (
    client.embeddings.create(input=query, model="snowflake-arctic-embed2:568m").data[0].embedding
)
len(query_embeddings)

1024

In [79]:
query_embeddings = (
    client.embeddings.create(input=query, model="granite-embedding:278m").data[0].embedding
)
len(query_embeddings)

768

In [83]:
pd_vectors.head(3)

,speaker,title,videoId,start,seconds,summary,ada_v2
0,"Seth Juarez, Josh Lovejoy, Sarah Bird",You're Not Solving the Problem You Think You'r...,-tJQm4mSh1s,00:00:00,0,Join Seth Juarez as he discusses ethical conce...,"[0.004357332363724, -0.028409153223037, 0.0111..."
1,"Seth Juarez, Josh Lovejoy, Sarah Bird",You're Not Solving the Problem You Think You'r...,-tJQm4mSh1s,00:03:07,187,"In this video, the speaker discusses the chall...","[-0.0038613036740570003, -0.004626247566193000..."
2,"Seth Juarez, Josh Lovejoy, Sarah Bird",You're Not Solving the Problem You Think You'r...,-tJQm4mSh1s,00:06:13,373,The video discusses the limitations of general...,"[0.00287682027556, -0.012365541420876001, 0.02..."

In [86]:
def calc_embedding(query):
    return (
        client.embeddings.create(input=query, model="nomic-embed-text:latest")
        .data[0]
        .embedding
    )


pd_vectors["nomic_embed_text"] = pd_vectors["summary"].apply(lambda x: calc_embedding(x))

In [87]:
pd_vectors.head(3)

,speaker,title,videoId,start,seconds,summary,ada_v2,nomic_embed_text
0,"Seth Juarez, Josh Lovejoy, Sarah Bird",You're Not Solving the Problem You Think You'r...,-tJQm4mSh1s,00:00:00,0,Join Seth Juarez as he discusses ethical conce...,"[0.004357332363724, -0.028409153223037, 0.0111...","[0.0053251395, 0.07696573, -0.12703636, -0.042..."
1,"Seth Juarez, Josh Lovejoy, Sarah Bird",You're Not Solving the Problem You Think You'r...,-tJQm4mSh1s,00:03:07,187,"In this video, the speaker discusses the chall...","[-0.0038613036740570003, -0.004626247566193000...","[-0.0021130424, 0.11187765, -0.16042458, -0.00..."
2,"Seth Juarez, Josh Lovejoy, Sarah Bird",You're Not Solving the Problem You Think You'r...,-tJQm4mSh1s,00:06:13,373,The video discusses the limitations of general...,"[0.00287682027556, -0.012365541420876001, 0.02...","[-0.032370586, 0.090112984, -0.13621558, -0.02..."

In [88]:
len(pd_vectors.at[0, 'nomic_embed_text'])

768

In [99]:
DATASET_NAME = "08-building-search-applications/scripts/embedding_index_3m_nomic.json"
pd_vectors.to_json(DATASET_NAME, orient='records')

In [98]:
import pandas
import pandas._version 
pandas._version.get_versions()

{'date': '2023-01-19T10:26:43+0700',
 'dirty': False,
 'error': None,
 'full-revisionid': '2e218d10984e9919f0296931d92ea851c6a6faf5',
 'version': '1.5.3'}

In [101]:
from tqdm import tqdm
import time

# 在 for 循环中使用
for i in tqdm(range(100)):
    # 模拟耗时操作
    time.sleep(0.05)

100%|██████████| 100/100 [00:05<00:00, 18.38it/s]

In [102]:
from tqdm import tqdm
import time

# 创建进度条对象
pbar = tqdm(total=100)

for i in range(100):
    # 模拟耗时操作
    time.sleep(0.05)
    # 手动更新进度
    pbar.update(1)  # 每次更新1

# 关闭进度条
pbar.close()

100%|██████████| 100/100 [00:05<00:00, 18.41it/s]

In [103]:
from tqdm import tqdm
import time

for i in tqdm(range(100), desc="处理进度"):
    time.sleep(0.05)

处理进度: 100%|██████████| 100/100 [00:05<00:00, 18.39it/s]

In [104]:
from tqdm import tqdm
import time

for i in tqdm(range(100), 
             bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}]"):
    time.sleep(0.05)

100%|██████████| 100/100 [00:05<00:00]

In [105]:
from tqdm.notebook import tqdm
import time

for i in tqdm(range(100)):
    time.sleep(0.05)

  0%|          | 0/100 [00:00<?, ?it/s]

In [106]:
from tqdm import tqdm
import time

data = [1, 2, 3, 4, 5]
for item in tqdm(data, desc="处理数据"):
    time.sleep(0.5)

处理数据: 100%|██████████| 5/5 [00:02<00:00,  1.98it/s]

In [107]:
from tqdm import tqdm
import time

for i in tqdm(range(5), desc="外层循环"):
    for j in tqdm(range(100), desc="内层循环", leave=False):
        time.sleep(0.01)

外层循环: 100%|██████████| 5/5 [00:06<00:00,  1.24s/it]

In [108]:
from tqdm.notebook import tqdm
import time

for i in tqdm(range(5), desc="外层循环"):
    for j in tqdm(range(100), desc="内层循环", leave=False):
        time.sleep(0.01)

外层循环:   0%|          | 0/5 [00:00<?, ?it/s]

内层循环:   0%|          | 0/100 [00:00<?, ?it/s]

内层循环:   0%|          | 0/100 [00:00<?, ?it/s]

内层循环:   0%|          | 0/100 [00:00<?, ?it/s]

内层循环:   0%|          | 0/100 [00:00<?, ?it/s]

内层循环:   0%|          | 0/100 [00:00<?, ?it/s]